@echo off
setlocal
cd /d "%~dp0"

echo ================================================================
echo   3DpicToIFC - one-time setup
echo ================================================================
echo.
echo This will check that Node.js and Python are installed, then
echo download the app's packages. You need an INTERNET CONNECTION.
echo The Python step downloads several gigabytes (AI libraries), so
echo the first setup can take 10-40 minutes depending on your speed.
echo.

rem ----------------------------------------------------------------
rem 1. Node.js
rem ----------------------------------------------------------------
where node >nul 2>nul
if errorlevel 1 goto :no_node
for /f "delims=" %%v in ('node --version') do set "NODE_VER=%%v"
echo [OK] Node.js found (%NODE_VER%)

rem ----------------------------------------------------------------
rem 2. Python 3.11+
rem ----------------------------------------------------------------
where python >nul 2>nul
if errorlevel 1 goto :no_python
python -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)" >nul 2>nul
if errorlevel 1 goto :old_python
for /f "delims=" %%v in ('python --version') do set "PY_VER=%%v"
echo [OK] %PY_VER% found

rem ----------------------------------------------------------------
rem 3. Node packages (npm ci from the lock file; fall back to install)
rem ----------------------------------------------------------------
echo.
echo [1/3] Installing Node.js packages (about 150 MB)...
call npm ci --omit=dev
if not errorlevel 1 goto :node_ok
echo      npm ci did not work - trying npm install instead...
call npm install --omit=dev
if errorlevel 1 goto :npm_fail
:node_ok
echo [OK] Node packages installed.

rem ----------------------------------------------------------------
rem 4. Python virtual environment + packages
rem ----------------------------------------------------------------
echo.
echo [2/3] Setting up the Python environment in .\pyenv ...
if exist "pyenv\Scripts\python.exe" goto :pip_install
python -m venv pyenv
if errorlevel 1 goto :venv_fail

:pip_install
echo      Downloading Python AI packages. THIS IS THE BIG ONE:
echo      several GB (PyTorch and friends). Please be patient...
"pyenv\Scripts\python.exe" -m pip install --upgrade pip
"pyenv\Scripts\python.exe" -m pip install -r requirements-app.txt
if errorlevel 1 goto :pip_fail
echo [OK] Python packages installed.

rem ----------------------------------------------------------------
rem 5. Write the .env config so the app uses THIS Python environment
rem    (never overwrites an existing .env)
rem ----------------------------------------------------------------
rem (written line-by-line so paths containing parentheses cannot break the block)
if exist ".env" goto :env_done
echo # Generated by setup.bat> .env
echo PORT=3000>> .env
echo HOST=localhost>> .env
echo NODE_ENV=production>> .env
echo MAX_FILE_SIZE=52428800>> .env
echo TEMP_DIR=./temp>> .env
echo UPLOAD_DIR=./uploads>> .env
echo OUTPUT_DIR=./outputs>> .env
echo PYTHON_PATH=%~dp0pyenv\Scripts\python.exe>> .env
echo PYTHON_SCRIPTS_DIR=./backend/python-scripts>> .env
echo ROOM_OUT_DIR=./demo/app_out>> .env
echo USE_GPU=true>> .env
echo CUDA_VISIBLE_DEVICES=0>> .env
echo IFC_OUTPUT_DIR=./outputs>> .env
echo LOG_LEVEL=info>> .env
echo [OK] Wrote .env configuration.
:env_done

rem ----------------------------------------------------------------
rem 6. Optional: SAM2 segmentation weights (better photo cut-outs).
rem    If this fails the app still works - it uses a built-in fallback.
rem ----------------------------------------------------------------
echo.
echo [3/3] Downloading optional segmentation weights (156 MB)...
if exist "models\sam2\sam2.1_hiera_tiny.pt" goto :sam2_done
where curl >nul 2>nul
if errorlevel 1 goto :sam2_skip
if not exist "models\sam2" mkdir "models\sam2"
curl -L -f --retry 2 -o "models\sam2\sam2.1_hiera_tiny.pt" "https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_tiny.pt"
if errorlevel 1 goto :sam2_cleanup
goto :sam2_done
:sam2_cleanup
if exist "models\sam2\sam2.1_hiera_tiny.pt" del "models\sam2\sam2.1_hiera_tiny.pt"
:sam2_skip
echo      Skipped - the app will use its built-in fallback. That is fine.
:sam2_done

echo.
echo ================================================================
echo   Setup complete - run start.bat
echo ================================================================
echo.
echo Note: the FIRST time you generate a 3D model, the app downloads
echo its AI model weights (a few more GB, one time only). Keep your
echo internet connection on for the first generation.
echo.
pause
exit /b 0

rem ================= error messages ===============================

:no_node
echo.
echo [PROBLEM] Node.js is not installed (or not on your PATH).
echo.
echo   Please install Node.js 20 LTS from:
echo       https://nodejs.org/en/download
echo.
echo   Use the "Windows Installer (.msi)" and accept the defaults.
echo   Then close this window and run setup.bat again.
echo.
pause
exit /b 1

:no_python
echo.
echo [PROBLEM] Python is not installed (or not on your PATH).
echo.
echo   Please install Python 3.11 or newer from:
echo       https://www.python.org/downloads/
echo.
echo   IMPORTANT: on the first installer screen, tick the box
echo       "Add python.exe to PATH"
echo   Then close this window and run setup.bat again.
echo.
pause
exit /b 1

:old_python
echo.
echo [PROBLEM] Your Python is too old. This app needs Python 3.11 or newer.
echo.
echo   Please install the latest Python from:
echo       https://www.python.org/downloads/
echo.
echo   IMPORTANT: on the first installer screen, tick the box
echo       "Add python.exe to PATH"
echo   Then close this window and run setup.bat again.
echo.
pause
exit /b 1

:npm_fail
echo.
echo [PROBLEM] Installing Node packages failed.
echo   Check your internet connection and run setup.bat again.
echo   If it keeps failing, delete the "node_modules" folder and retry.
echo.
pause
exit /b 1

:venv_fail
echo.
echo [PROBLEM] Could not create the Python environment (.\pyenv).
echo   Try deleting the "pyenv" folder and running setup.bat again.
echo.
pause
exit /b 1

:pip_fail
echo.
echo [PROBLEM] Installing Python packages failed.
echo   This is usually a network hiccup during the large PyTorch
echo   download. Run setup.bat again - it resumes where it left off.
echo.
pause
exit /b 1
